apiVersion: v1
kind: Secret
metadata:
  name: mysql-credenciales
  namespace: mysql-externo
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Semeolvido8."
  MYSQL_DATABASE: "appdb"
  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: "Semeolvido8."
