# Utiliza la StorageClass predeterminada del clúster.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-datos
  namespace: mysql-externo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
