apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-externo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql-externo
  template:
    metadata:
      labels:
        app: mysql-externo
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-credenciales
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: '1'
              memory: 1Gi
          volumeMounts:
            - name: datos
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 --silent
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: datos
          persistentVolumeClaim:
            claimName: mysql-datos
